create table if not exists users(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(255),
chat_id BIGINT NOT NULL
);

create table if not exists histories(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
chat_id BIGINT NOT NULL,
town VARCHAR(255),
response VARCHAR(255),
request_time TIMESTAMP
);